---
title: Multi-Factor Authentication (MFA / OTP)
description: Specification for two-step verification using Time-based One-Time Passwords (TOTP via Google Authenticator/Authy) and SMS/Email OTP.
---

# 🛡️ Multi-Factor Authentication (MFA)

## 🎯 1. Business Objective
MFA introduces a secondary security barrier requiring a 6-digit TOTP code generated by an Authenticator app (or SMS/Email) after passing the primary [Email & Password Login Flow](/docs/auth/login-flow).

---

## 🛠️ 2. Enrollment & Setup Workflow

1. **Enrollment**: Users initiate setup inside [Account Security Settings](/docs/user/profile-management/account-settings) by scanning a QR code to generate a shared secret key (TOTP).
2. **Verification**: Entering a valid 6-digit code confirms successful setup.
3. **Backup Codes**: System generates 8 single-use emergency recovery codes for account retrieval if the device is lost.

---

## 🔄 3. Authentication Sequence

```mermaid
sequenceDiagram
    autonumber
    actor User as End User
    participant App as Frontend Client
    participant Auth as Auth Server (MFA)
    participant UserDB as User Database

    User->>App: 1. Submit 6-digit OTP Code
    App->>Auth: 2. POST /api/v1/auth/mfa/verify
    Auth->>Auth: 3. Validate Secret Key & HMAC-SHA1
    alt Valid OTP Code
        Auth->>UserDB: 4. Update last_login_at
        Auth-->>App: 5. Query Roles/Permissions & Issue Access Token
        App-->>User: 6. Redirect to User Profile
    else Invalid / Expired OTP (30s Window)
        Auth-->>App: 5. Error 400: Invalid OTP Code
        App-->>User: 6. Display verification failure message
    end
```

---

## 🔗 4. Related References

- 🔙 **Primary Login**: [Standard Login Flow](/docs/auth/login-flow).
- ⚙️ **Enable/Disable MFA**: Configure 2FA preferences in [Account Settings](/docs/user/profile-management/account-settings).
- 🔑 **Session Issuance**: Learn token details in [Session Management](/docs/auth/oauth-sso/session-management).
